variables:
  IMAGE_TAG: "2020-03-05-1"
  LINARO_TOOLCHAIN_URL: "https://releases.linaro.org/components/toolchain/binaries/7.5-2019.12/aarch64-linux-gnu/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz"

stages:
  - docker
  - build

build:docker:
  stage: docker
  tags: 
    - docker
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$IMAGE_TAG && exit 0 || true
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$IMAGE_TAG --tag $CI_REGISTRY_IMAGE:latest ./
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:latest

build:initrd:
  tags: 
    - docker
  stage: build
  image: $CI_REGISTRY_IMAGE:$IMAGE_TAG
  
  before_script:
    - git clone https://github.com/u-boot/u-boot --branch=master --depth=1 /tmp/u-boot
    - wget -qO- $LINARO_TOOLCHAIN_URL  | tar -xJ --strip-components=1 -C /tmp/toolchain

  script:
    - bash build.sh /tmp/toolchain /tmp/u-boot libretech-cc

  after_script:
    - cp build_libretech-cc/u-boot.bin results/u-boot_libretech-cc.bin

  artifacts:
    when: always
    paths:
      - results/
